name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Release and Push
    runs-on: ubuntu-24.04
    if: contains(github.event.head_commit.message, '#RELEASE')
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create a Single Tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y%m%d')
          echo "TAG_NAME=v${VERSION}" >> $GITHUB_ENV
          echo "Created TAG_NAME=$TAG_NAME"

      - name: Build IP API Binary for Release
        run: |
          IP_API_BINARY_NAME=echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            IP_API_BINARY_NAME="${IP_API_BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o $IP_API_BINARY_NAME -a -ldflags="-s -w" -installsuffix cgo web/echo-ip-api/main.go

      - name: Build DNS API Binary for Release
        run: |
          DNS_API_BINARY_NAME=echo-dns-api-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            DNS_API_BINARY_NAME="${DNS_API_BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o $DNS_API_BINARY_NAME -a -ldflags="-s -w" -installsuffix cgo web/echo-dns-api/main.go

      - name: Build CMD Binary for Release
        run: |
          CMD_BINARY_NAME=echo-ip-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            CMD_BINARY_NAME="${CMD_BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o $CMD_BINARY_NAME -a -ldflags="-s -w" -installsuffix cgo cmd/echo-ip/main.go

      - name: Verify Binary Existence
        run: |
          IP_API_BINARY_NAME=echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}
          DNS_API_BINARY_NAME=echo-dns-api-${{ matrix.os }}-${{ matrix.arch }}
          CMD_BINARY_NAME=echo-ip-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            IP_API_BINARY_NAME="${IP_API_BINARY_NAME}.exe"
            DNS_API_BINARY_NAME="${DNS_API_BINARY_NAME}.exe"
            CMD_BINARY_NAME="${CMD_BINARY_NAME}.exe"
          fi
          echo "Verifying ip-api binary existence..."
          ls -la $IP_API_BINARY_NAME
          echo "Verifying dns-api binary existence..."
          ls -la $DNS_API_BINARY_NAME
          echo "Verifying cmd binary existence..."
          ls -la $CMD_BINARY_NAME

      - name: Upload Release Assets
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: echo-ip-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}*
            echo-dns-api-${{ matrix.os }}-${{ matrix.arch }}*
            echo-ip-${{ matrix.os }}-${{ matrix.arch }}*

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: |
            echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}*
            echo-dns-api-${{ matrix.os }}-${{ matrix.arch }}*
            echo-ip-${{ matrix.os }}-${{ matrix.arch }}*
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}