name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Release and Push
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#RELEASE')
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Create a Single Tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y%m%d')
          echo "TAG_NAME=v${VERSION}" >> $GITHUB_ENV
          echo "Created TAG_NAME=$TAG_NAME"

      - name: Build Root Binary for Release
        run: |
          ROOT_BINARY_NAME=echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            ROOT_BINARY_NAME="${ROOT_BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o $ROOT_BINARY_NAME -a -ldflags="-s -w" -installsuffix cgo .

      - name: Build CMD Binary for Release
        run: |
          CMD_BINARY_NAME=echo-ip-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            CMD_BINARY_NAME="${CMD_BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o $CMD_BINARY_NAME -a -ldflags="-s -w" -installsuffix cgo cmd/echo-ip/main.go

      - name: Verify Binary Existence
        run: |
          ROOT_BINARY_NAME=echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}
          CMD_BINARY_NAME=echo-ip-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            ROOT_BINARY_NAME="${ROOT_BINARY_NAME}.exe"
            CMD_BINARY_NAME="${CMD_BINARY_NAME}.exe"
          fi
          echo "Verifying root binary existence..."
          ls -la $ROOT_BINARY_NAME
          echo "Verifying cmd binary existence..."
          ls -la $CMD_BINARY_NAME

      - name: Upload Release Assets
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: echo-ip-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}*
            echo-ip-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}*

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: |
            echo-ip-api-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}*
            echo-ip-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TAG_NAME }}*
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}